posta threads
DadosAbertosDeFeira/diario-de-feira pull request #18
Opened 2021-09-14 12:30 UTC by luandadantas

- Posta threads
- Palavras configuráveis

2021-09-23 09:36 UTC, anapaulagomes commented on diario/main.py
> +            character_number = sum([len(topic_len) for topic_len in found_topics])
```suggestion
            character_number = sum(len(topic_len) for topic_len in found_topics)
```

2021-09-23 09:48 UTC, anapaulagomes requested changes
Muito bom, @luandadantas! Gostei de ter incluído a divisão de tweets nesse PR. Você brilhou nos testes! ✨ 

Deixei algumas sugestões de melhoria no código mas nada demais. Assim que você finalizar nós mergeamos.

2021-09-23 09:48 UTC, anapaulagomes commented on diario/main.py
> +                tweet_id = tweet(reply_message, tweet_id)
```suggestion
                tweet(reply_message, tweet_id)
```
Não precisamos dessa variável aqui porque ela não será usada depois.

2021-09-23 09:48 UTC, anapaulagomes commented on diario/main.py
> +                    if tweets[0] == post:
Essa condição sempre vai ser verdadeira para o primeiro item, afinal eles são o mesmo. Mas não fica tão claro ao ler de maneira rápida o código. Poderíamos fazer de duas formas aqui:

1) Adicionar um índice e verificar se é o primeiro ou não.

```
                for index, post in enumerate(tweets):
                    if index == 0:
                        reply_message = f"Nele temos: {', '.join(post)}"
                    else:
                        reply_message = f"Temos também: {', '.join(post)}"
                    tweet_id = tweet(reply_message, tweet_id)
                    logger.info("The thread was posted")
```

2) Chamar o primeiro da sequência de tweets fora do loop:

```
                reply_message = f"Nele temos: {', '.join(post)}"
                tweet_id = tweet(reply_message, tweet_id)
                
                for post in tweets[1:]:
                    reply_message = f"Temos também: {', '.join(post)}"
                    tweet_id = tweet(reply_message, tweet_id)
                    logger.info("The thread was posted")
```

Fica a teu critério (pode sugerir outras coisas também).

2021-09-23 09:48 UTC, anapaulagomes commented on diario/meaning.py
> +def split_tweets(found_topics: list, character_limit: int):
Acho que podemos mover esse método para um outro módulo depois porque ele não tem muito a ver com o significado do conteúdo diário mas sim com as restrições do Twitter. Faz sentido?

2021-09-23 09:48 UTC, anapaulagomes commented on diario/meaning.py
> +    return tweet_list
O [sourcery](https://sourcery.ai/) recomendou esse refactor e acho que ficou mais claro:

```suggestion
def split_tweets(found_topics: list, character_limit: int):
    tweet = []
    tweet_list = []
    character_sum = 0

    for word in found_topics:
        if character_sum + len(word) >= character_limit:
            tweet_list.append(tweet)
            tweet = []
        tweet.append(word)
        character_sum = sum(len(item) for item in tweet)

    tweet_list.append(tweet)
    return tweet_list
```

2021-09-23 09:48 UTC, anapaulagomes commented on tests/test_main.py
> +    )
Muito bom! 🏆

2021-09-24 16:43 UTC, luandadantas commented on diario/main.py
> +                    if tweets[0] == post:
Não conhecia o enumerate, tô usando ele. :)

2021-09-24 16:47 UTC, luandadantas commented on diario/meaning.py
> +def split_tweets(found_topics: list, character_limit: int):
Siim! Faz total sentido, pensei em algo como utils pra o nome do módulo, daí podemos colocar essas funções auxiliares pra lá. Mas se esse nome é ruim, pode me dizer tbm rsrsrs..

2021-09-24 17:08 UTC, anapaulagomes commented on diario/meaning.py
> +def split_tweets(found_topics: list, character_limit: int):
Vemos isso depois! haha

2021-09-24 17:09 UTC, anapaulagomes approved these changes

2021-09-24 17:09 UTC, merged